name: Build & Push Docker image

on:
  workflow_call:
    inputs:
      image-name:
        description: "Name of the Docker image"
        required: true
        type: string
      dockerfile:
        description: "Path to the Dockerfile"
        required: false
        default: Dockerfile
        type: string
      context:
        description: "Build context"
        required: false
        default: .
        type: string
      tags:
        description: "Comma-separated list of tags (e.g., latest,1.0.0)"
        required: false
        default: latest
        type: string
      registry:
        description: "Registry URL"
        required: false
        default: ghcr.io
        type: string
    secrets:
      GHCR_TOKEN:
        description: "Token with permission to push to GitHub Container Registry"
        required: true
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: |
            ${{ join(fromJson('["ghcr.io/' || github.repository_owner || '/' || inputs.image-name || ':' || replace(inputs.tags, ',', '","') || '"]'), '\n') }}
